- name: Create nginx directory
  file:
    path: /etc/nginx
    state: directory
    mode: 0755

- name: Copy NGINX configuration file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Install custom NGINX load balancer in Docker container
  docker_container:
    name: load-balancer
    image: ghcr.io/zdenekvavricka/dce-semestralka_1-load_balancer:v1.0.1
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"